language: php

php: [5.3, 5.4, 5.5, 5.6, 7.0, 7.1, hhvm]

branches:
  except:
    - /^bugfix\/.*$/
    - /^feature\/.*$/
    - /^optimization\/.*$/

before_script:
  - composer install --dev --prefer-source

script:
  - phpunit
